import assert from "node:assert/strict";
import test from "node:test";
import { verifyChatwootWebhook, claimChatwootDelivery } from "../lib/chatwoot-webhook.ts";
import { LocalD1Database } from "./helpers/local-bindings.mjs";
const secret="test-webhook-secret", now=1_700_000_000_000, base={event:"contact_created",account:{id:1}};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
async function req(raw,{timestamp=now/1000,valid=true,delivery="d-1",type="application/json"}={}){const e=new TextEncoder(),k=await crypto.subtle.importKey("raw",e.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),sig=`sha256=${hex(await crypto.subtle.sign("HMAC",k,e.encode(`${timestamp}.${raw}`)))}`;return new Request("http://local",{headers:{"content-type":type,"x-chatwoot-timestamp":String(timestamp),"x-chatwoot-signature":valid?sig:"sha256=bad",...(delivery?{"x-chatwoot-delivery":delivery}:{})}});}
test("accepts four events and stable fallback",async()=>{for(const event of ["contact_created","contact_updated","conversation_created","conversation_updated"]){const raw=JSON.stringify({...base,event});assert.equal((await verifyChatwootWebhook(await req(raw,{delivery:""}),raw,secret,now)).supported,true);}const raw=JSON.stringify(base),a=await verifyChatwootWebhook(await req(raw,{delivery:""}),raw,secret,now),b=await verifyChatwootWebhook(await req(raw,{delivery:""}),raw,secret,now);assert.equal(a.delivery,b.delivery);});
test("rejects invalid signature, timestamp, content type and json",async()=>{const raw=JSON.stringify(base),bad=await req(raw,{valid:false}),old=await req(raw,{timestamp:now/1000-301}),plain=await req(raw,{type:"text/plain"});await assert.rejects(()=>verifyChatwootWebhook(bad,raw,secret,now));await assert.rejects(()=>verifyChatwootWebhook(old,raw,secret,now));await assert.rejects(()=>verifyChatwootWebhook(plain,raw,secret,now));const x=await req("{");await assert.rejects(()=>verifyChatwootWebhook(x,"{",secret,now));});
function db(){const value=new LocalD1Database();value.sqlite.exec("CREATE TABLE crm_operations (operation_id TEXT PRIMARY KEY, operation_type TEXT NOT NULL, request_hash TEXT NOT NULL, status TEXT, response_json TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TEXT)");return value;}
test("persists delivery claims, retains distinct deliveries and cleans old receipts",async()=>{const value=db();assert.equal(await claimChatwootDelivery(value,"one"),true);assert.equal(await claimChatwootDelivery(value,"one"),false);assert.equal(await claimChatwootDelivery(value,"two"),true);assert.equal(value.sqlite.prepare("SELECT count(*) n FROM crm_operations").get().n,2);value.sqlite.exec("UPDATE crm_operations SET created_at=datetime('now','-8 days') WHERE operation_id='chatwoot-one'");await claimChatwootDelivery(value,"three");assert.equal(value.sqlite.prepare("SELECT count(*) n FROM crm_operations WHERE operation_id='chatwoot-one'").get().n,0);value.close();});
test("concurrent claim has exactly one winner",async()=>{const value=db();const results=await Promise.all([claimChatwootDelivery(value,"same"),claimChatwootDelivery(value,"same")]);assert.deepEqual(results.sort(),[false,true]);assert.equal(value.sqlite.prepare("SELECT count(*) n FROM crm_operations").get().n,1);value.close();});
