import { ensureDatabase, getD1 } from "@/db";
import { authenticateCrmRequest } from "@/lib/crm-auth";
import { CrmError, addCustomerIdentity, createCrmOrder, createCustomer, customerOrders, getCustomer, linkChatwootContact, linkChatwootConversationOrder, resolveCustomer, searchCrmProducts, updateCustomer } from "@/lib/crm";
import { loadOrder } from "@/lib/orders-service";

type Context={params:Promise<{path:string[]}>};
function response(error:unknown) { const item=error instanceof CrmError?error:new CrmError("Error interno de CRM.",500,"CRM_INTERNAL_ERROR"); return Response.json({error:{code:item.code,message:item.message}},{status:item.status}); }
async function secured(request:Request) { const raw=["GET","HEAD"].includes(request.method)?"":await request.text(); await authenticateCrmRequest(request,raw); return raw?JSON.parse(raw) as Record<string,unknown>:{}; }
function operation(input:Record<string,unknown>) { const value=typeof input.operationId==="string"?input.operationId.trim():""; if(!/^[A-Za-z0-9_-]{8,160}$/.test(value)) throw new CrmError("operationId es obligatorio para escrituras CRM.",400,"CRM_OPERATION_ID_REQUIRED"); return value; }
async function idempotent(db:D1Database, type:string, operationId:string, input:Record<string,unknown>, action:()=>Promise<unknown>) { const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(input))); const requestHash=[...new Uint8Array(hash)].map((n)=>n.toString(16).padStart(2,"0")).join(""); const existing=await db.prepare("SELECT request_hash,response_json FROM crm_operations WHERE operation_id=?").bind(operationId).first<{request_hash:string;response_json:string|null}>(); if(existing){if(existing.request_hash!==requestHash) throw new CrmError("operationId ya fue utilizado con otro payload.",409,"CRM_IDEMPOTENCY_CONFLICT"); if(!existing.response_json) throw new CrmError("La operación está en curso.",409,"CRM_OPERATION_PENDING"); return JSON.parse(existing.response_json);}
  await db.prepare("INSERT INTO crm_operations (operation_id,operation_type,request_hash) VALUES (?,?,?)").bind(operationId,type,requestHash).run(); try { const result=await action(); await db.prepare("UPDATE crm_operations SET status='COMPLETED',response_json=?,completed_at=CURRENT_TIMESTAMP WHERE operation_id=?").bind(JSON.stringify(result),operationId).run(); return result; } catch(error) { await db.prepare("DELETE FROM crm_operations WHERE operation_id=? AND status='PENDING'").bind(operationId).run(); throw error; }
}
export async function GET(request:Request,context:Context) { try { await secured(request); await ensureDatabase(); const p=(await context.params).path; const db=getD1(); if(p[0]==="customers"&&p[1]==="resolve") return Response.json({customer:await resolveCustomer(db,Object.fromEntries(new URL(request.url).searchParams))}); if(p[0]==="customers"&&p[2]==="orders") return Response.json({orders:await customerOrders(db,p[1],false)}); if(p[0]==="customers"&&p[2]==="active-orders") return Response.json({orders:await customerOrders(db,p[1],true)}); if(p[0]==="customers"&&p.length===2){const result=await getCustomer(db,p[1]);if(!result)throw new CrmError("Cliente no encontrado.",404,"CRM_CUSTOMER_NOT_FOUND");return Response.json({customer:result});} if(p[0]==="products"&&p[1]==="search")return Response.json({products:await searchCrmProducts(db,new URL(request.url).searchParams.get("q")??"")}); if(p[0]==="orders"&&p[2]==="summary"){const order=await loadOrder(db,p[1]);if(!order)throw new CrmError("Pedido no encontrado.",404,"CRM_ORDER_NOT_FOUND");return Response.json({order});} throw new CrmError("Ruta CRM no encontrada.",404,"CRM_ROUTE_NOT_FOUND"); }catch(error){return response(error);} }
export async function POST(request:Request,context:Context) { try { const input=await secured(request); await ensureDatabase(); const db=getD1(); const p=(await context.params).path; const op=operation(input); let result:unknown; if(p.join("/")==="customers")result=await idempotent(db,"CUSTOMER_CREATE",op,input,()=>createCustomer(db,input)); else if(p.join("/")==="customer-identities")result=await idempotent(db,"CUSTOMER_IDENTITY",op,input,()=>addCustomerIdentity(db,input)); else if(p.join("/")==="chatwoot/contact-links")result=await idempotent(db,"CHATWOOT_CONTACT_LINK",op,input,()=>linkChatwootContact(db,input)); else if(p.join("/")==="chatwoot/conversation-order-links")result=await idempotent(db,"CHATWOOT_CONVERSATION_ORDER_LINK",op,input,()=>linkChatwootConversationOrder(db,input)); else if(p.join("/")==="orders")result=await idempotent(db,"CRM_ORDER_CREATE",op,input,()=>createCrmOrder(db,input)); else throw new CrmError("Ruta CRM no encontrada.",404,"CRM_ROUTE_NOT_FOUND"); return Response.json(result,{status:201}); }catch(error){return response(error);} }
export async function PATCH(request:Request,context:Context) { try { const input=await secured(request); await ensureDatabase(); const p=(await context.params).path; if(p[0]!=="customers"||p.length!==2)throw new CrmError("Ruta CRM no encontrada.",404,"CRM_ROUTE_NOT_FOUND"); const db=getD1(); return Response.json(await idempotent(db,"CUSTOMER_UPDATE",operation(input),input,()=>updateCustomer(db,p[1],input))); }catch(error){return response(error);} }
