export const FINANCE_DATABASE_SQL = [
  `CREATE TABLE IF NOT EXISTS finance_sales (
    id TEXT PRIMARY KEY NOT NULL,
    order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    order_number TEXT NOT NULL,
    customer_name_snapshot TEXT NOT NULL,
    delivered_at TEXT NOT NULL,
    route_id TEXT,
    currency TEXT NOT NULL DEFAULT 'CRC',
    product_gross_total INTEGER NOT NULL,
    discount_total INTEGER NOT NULL DEFAULT 0,
    product_net_total INTEGER NOT NULL,
    delivery_income INTEGER NOT NULL DEFAULT 0,
    total_income INTEGER NOT NULL,
    historical_cogs_total INTEGER,
    cost_status TEXT NOT NULL DEFAULT 'MISSING' CHECK (cost_status IN ('COMPLETE','MISSING')),
    source_operation_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'RECOGNIZED' CHECK (status IN ('RECOGNIZED','REVERSED')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at TEXT,
    CHECK (product_gross_total >= 0 AND discount_total >= 0 AND product_net_total >= 0 AND delivery_income >= 0 AND total_income >= 0 AND (historical_cogs_total IS NULL OR historical_cogs_total >= 0))
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_sales_source_operation_unique ON finance_sales (source_operation_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_sales_active_order_unique ON finance_sales (order_id) WHERE status='RECOGNIZED'",
  "CREATE INDEX IF NOT EXISTS finance_sales_delivered_idx ON finance_sales (delivered_at,id)",
  "CREATE INDEX IF NOT EXISTS finance_sales_route_idx ON finance_sales (route_id,delivered_at,id)",
  `CREATE TABLE IF NOT EXISTS finance_sale_lines (
    id TEXT PRIMARY KEY NOT NULL,
    sale_id TEXT NOT NULL REFERENCES finance_sales(id) ON DELETE RESTRICT,
    order_line_id TEXT NOT NULL REFERENCES order_lines(id) ON DELETE RESTRICT,
    product_id INTEGER,
    product_name_snapshot TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_real INTEGER NOT NULL,
    gross_income INTEGER NOT NULL,
    allocated_discount INTEGER NOT NULL DEFAULT 0,
    net_income INTEGER NOT NULL,
    historical_unit_cost INTEGER,
    historical_cogs INTEGER,
    gross_profit INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (unit_price_real >= 0 AND gross_income >= 0 AND allocated_discount >= 0 AND net_income >= 0 AND (historical_unit_cost IS NULL OR historical_unit_cost >= 0) AND (historical_cogs IS NULL OR historical_cogs >= 0))
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_sale_lines_sale_order_line_unique ON finance_sale_lines (sale_id,order_line_id)",
  "CREATE INDEX IF NOT EXISTS finance_sale_lines_product_idx ON finance_sale_lines (product_id,sale_id)",
  `CREATE TABLE IF NOT EXISTS finance_sale_events (
    id TEXT PRIMARY KEY NOT NULL,
    sale_id TEXT NOT NULL REFERENCES finance_sales(id) ON DELETE RESTRICT,
    event_type TEXT NOT NULL CHECK (event_type IN ('RECOGNITION','REVERSAL')),
    source_operation_id TEXT NOT NULL,
    reason TEXT,
    previous_json TEXT NOT NULL DEFAULT '{}',
    next_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_sale_events_operation_unique ON finance_sale_events (source_operation_id,event_type)",
  "CREATE INDEX IF NOT EXISTS finance_sale_events_sale_idx ON finance_sale_events (sale_id,created_at,id)",
  `CREATE TABLE IF NOT EXISTS finance_expenses (
    id TEXT PRIMARY KEY NOT NULL,
    expense_date TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount_crc INTEGER NOT NULL,
    original_amount_minor INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'CRC',
    exchange_rate_crc INTEGER NOT NULL DEFAULT 1,
    payment_method TEXT NOT NULL CHECK (payment_method IN ('CASH','SINPE','CARD','OTHER')),
    provider TEXT,
    notes TEXT,
    route_id TEXT,
    order_id TEXT REFERENCES orders(id) ON DELETE RESTRICT,
    source_type TEXT NOT NULL DEFAULT 'MANUAL',
    source_id TEXT,
    idempotency_key TEXT NOT NULL,
    entry_type TEXT NOT NULL DEFAULT 'EXPENSE' CHECK (entry_type IN ('EXPENSE','REVERSAL')),
    reverses_expense_id TEXT,
    business_scope TEXT NOT NULL DEFAULT 'BUSINESS' CHECK (business_scope IN ('BUSINESS','PERSONAL')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (amount_crc > 0 AND original_amount_minor > 0 AND exchange_rate_crc > 0),
    CHECK ((entry_type='EXPENSE' AND reverses_expense_id IS NULL) OR (entry_type='REVERSAL' AND reverses_expense_id IS NOT NULL))
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_expenses_idempotency_unique ON finance_expenses (idempotency_key)",
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_expenses_reversal_unique ON finance_expenses (reverses_expense_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_expenses_source_unique ON finance_expenses (source_type,source_id) WHERE entry_type='EXPENSE' AND source_id IS NOT NULL",
  "CREATE INDEX IF NOT EXISTS finance_expenses_date_idx ON finance_expenses (expense_date,id)",
  "CREATE INDEX IF NOT EXISTS finance_expenses_route_idx ON finance_expenses (route_id,expense_date,id)",
  "CREATE INDEX IF NOT EXISTS finance_expenses_order_idx ON finance_expenses (order_id,expense_date,id)",
  `CREATE TABLE IF NOT EXISTS finance_recurring_templates (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    amount_crc INTEGER NOT NULL CHECK (amount_crc > 0),
    currency TEXT NOT NULL DEFAULT 'CRC',
    exchange_rate_crc INTEGER NOT NULL DEFAULT 1 CHECK (exchange_rate_crc > 0),
    payment_method TEXT NOT NULL CHECK (payment_method IN ('CASH','SINPE','CARD','OTHER')),
    frequency TEXT NOT NULL CHECK (frequency IN ('WEEKLY','MONTHLY','QUARTERLY','YEARLY')),
    next_due_date TEXT NOT NULL,
    provider TEXT,
    notes TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  "CREATE INDEX IF NOT EXISTS finance_recurring_due_idx ON finance_recurring_templates (active,next_due_date,id)",
  `CREATE TABLE IF NOT EXISTS finance_budgets (
    id TEXT PRIMARY KEY NOT NULL,
    category TEXT NOT NULL,
    year_month TEXT NOT NULL,
    amount_crc INTEGER NOT NULL CHECK (amount_crc > 0),
    operation_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_budgets_category_month_unique ON finance_budgets (category,year_month)",
  "CREATE UNIQUE INDEX IF NOT EXISTS finance_budgets_operation_unique ON finance_budgets (operation_id)",
] as const;
