import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const settings = sqliteTable("settings", {
  id: integer("id").primaryKey(),
  exchangeRateCrc: integer("exchange_rate_crc").notNull().default(520),
  courierRateUsdCents: integer("courier_rate_usd_cents").notNull().default(550),
  extraWeightMilliLb: integer("extra_weight_milli_lb").notNull().default(100),
  deliveryCrc: integer("delivery_crc").notNull().default(1000),
  correosCrc: integer("correos_crc").notNull().default(500),
  gamProfitCrc: integer("gam_profit_crc").notNull().default(5000),
  puertoProfitCrc: integer("puerto_profit_crc").notNull().default(4000),
  roundingCrc: integer("rounding_crc").notNull().default(100),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const products = sqliteTable("products", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  code: text("code"),
  brand: text("brand"),
  presentation: text("presentation"),
  purchasePriceUsdCents: integer("purchase_price_usd_cents"),
  weightMilliLb: integer("weight_milli_lb"),
  quantityAvailable: integer("quantity_available").notNull().default(0),
  minimumStock: integer("minimum_stock").notNull().default(0),
  minimumStockEnabled: integer("minimum_stock_enabled", { mode: "boolean" }).notNull().default(false),
  restockPurchasedAt: text("restock_purchased_at"),
  zeroStockSince: text("zero_stock_since"),
  version: integer("version").notNull().default(1),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("products_normalized_name_unique").on(table.normalizedName),
  uniqueIndex("products_code_unique").on(table.code),
]);

export const nonInventoryQuotes = sqliteTable("non_inventory_quotes", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  code: text("code"),
  purchasePriceUsdCents: integer("purchase_price_usd_cents"),
  weightMilliLb: integer("weight_milli_lb"),
  version: integer("version").notNull().default(1),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("non_inventory_quotes_updated_idx").on(table.updatedAt, table.id)]);

export const mutationReceipts = sqliteTable("mutation_receipts", {
  id: text("id").primaryKey(),
  status: text("status").notNull().default("pending"),
  responseJson: text("response_json"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
});

export const inventoryDocuments = sqliteTable("inventory_documents", {
  id: text("id").primaryKey(),
  fileFingerprint: text("file_fingerprint").notNull(),
  fileName: text("file_name").notNull(),
  mimeTypesJson: text("mime_types_json").notNull().default("[]"),
  provider: text("provider").notNull().default("other"),
  orderNumber: text("order_number"),
  invoiceNumber: text("invoice_number"),
  shipmentNumber: text("shipment_number"),
  documentDate: text("document_date"),
  pageCount: integer("page_count").notNull().default(1),
  fileCount: integer("file_count").notNull().default(0),
  processingMode: text("processing_mode").notNull().default("manual"),
  analysisStatus: text("analysis_status").notNull().default("not_requested"),
  activeAnalysisId: text("active_analysis_id"),
  fieldEvidenceJson: text("field_evidence_json").notNull().default("{}"),
  status: text("status").notNull().default("draft"),
  warningsJson: text("warnings_json").notNull().default("[]"),
  duplicateOf: text("duplicate_of"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  confirmedAt: text("confirmed_at"),
  confirmedBy: text("confirmed_by"),
}, (table) => [
  uniqueIndex("inventory_documents_fingerprint_unique").on(table.fileFingerprint),
  index("inventory_documents_history_idx").on(table.createdAt, table.id),
  index("inventory_documents_order_idx").on(table.provider, table.orderNumber, table.shipmentNumber),
]);

export const inventoryDocumentLines = sqliteTable("inventory_document_lines", {
  id: text("id").primaryKey(),
  documentId: text("document_id").notNull(),
  lineKey: text("line_key").notNull(),
  lineIndex: integer("line_index").notNull().default(0),
  pageNumber: integer("page_number"),
  originalDescription: text("original_description").notNull(),
  name: text("name").notNull(),
  brand: text("brand"),
  presentation: text("presentation"),
  size: text("size"),
  flavor: text("flavor"),
  concentration: text("concentration"),
  billedQuantity: integer("billed_quantity"),
  receivedQuantity: integer("received_quantity"),
  unitsPerPackage: integer("units_per_package").notNull().default(1),
  totalToAdd: integer("total_to_add").notNull().default(0),
  barcode: text("barcode"),
  canonicalBarcode: text("canonical_barcode"),
  barcodeType: text("barcode_type"),
  secondaryId: text("secondary_id"),
  secondaryType: text("secondary_type"),
  barcodeMethod: text("barcode_method"),
  barcodeSource: text("barcode_source"),
  barcodeSourceUrl: text("barcode_source_url"),
  barcodeSourceTitle: text("barcode_source_title"),
  barcodeDifferencesJson: text("barcode_differences_json").notNull().default("[]"),
  barcodeLookupStatus: text("barcode_lookup_status").notNull().default("pending"),
  fieldEvidenceJson: text("field_evidence_json").notNull().default("{}"),
  barcodeConfirmed: integer("barcode_confirmed").notNull().default(0),
  selectedForIngress: integer("selected_for_ingress").notNull().default(1),
  reviewSavedAt: text("review_saved_at"),
  confidence: integer("confidence").notNull().default(0),
  status: text("status").notNull().default("requires_confirm_code"),
  matchProductId: integer("match_product_id"),
  matchNonInventoryId: integer("match_non_inventory_id"),
  action: text("action").notNull().default("pending"),
  barcodeLevel: text("barcode_level"),
  warningsJson: text("warnings_json").notNull().default("[]"),
  processedOperationId: text("processed_operation_id"),
  ignoredReason: text("ignored_reason"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("inventory_document_lines_key_unique").on(table.documentId, table.lineKey),
  index("inventory_document_lines_document_idx").on(table.documentId, table.status, table.id),
  index("inventory_document_lines_barcode_idx").on(table.canonicalBarcode),
]);

export const inventoryDocumentFiles = sqliteTable("inventory_document_files", {
  id: text("id").primaryKey(),
  documentId: text("document_id").notNull(),
  fileIndex: integer("file_index").notNull(),
  storageKey: text("storage_key").notNull(),
  fileName: text("file_name").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  fileSha256: text("file_sha256").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("inventory_document_files_order_unique").on(table.documentId, table.fileIndex),
  uniqueIndex("inventory_document_files_storage_unique").on(table.storageKey),
  index("inventory_document_files_document_idx").on(table.documentId, table.fileIndex),
]);

export const invoiceAiAnalyses = sqliteTable("invoice_ai_analyses", {
  id: text("id").primaryKey(),
  documentId: text("document_id").notNull(),
  fileFingerprint: text("file_fingerprint").notNull(),
  analysisNumber: integer("analysis_number").notNull(),
  model: text("model").notNull(),
  status: text("status").notNull().default("processing"),
  responseId: text("response_id"),
  inputTokens: integer("input_tokens").notNull().default(0),
  cachedInputTokens: integer("cached_input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  webSearchCount: integer("web_search_count").notNull().default(0),
  estimatedCostMicrousd: integer("estimated_cost_microusd").notNull().default(0),
  extractionJson: text("extraction_json").notNull().default("{}"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  reanalysis: integer("reanalysis", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
}, (table) => [
  uniqueIndex("invoice_ai_analyses_number_unique").on(table.documentId, table.analysisNumber),
  index("invoice_ai_analyses_document_idx").on(table.documentId, table.createdAt),
  index("invoice_ai_analyses_usage_idx").on(table.createdAt, table.estimatedCostMicrousd),
]);

export const supplierProductAliases = sqliteTable("supplier_product_aliases", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  provider: text("provider").notNull(),
  secondaryType: text("secondary_type").notNull(),
  secondaryId: text("secondary_id").notNull(),
  barcode: text("barcode").notNull(),
  canonicalBarcode: text("canonical_barcode").notNull(),
  productId: integer("product_id").notNull(),
  descriptionSignature: text("description_signature").notNull(),
  presentationSignature: text("presentation_signature"),
  unitsPerPackage: integer("units_per_package").notNull().default(1),
  barcodeLevel: text("barcode_level").notNull().default("unit"),
  source: text("source"),
  confirmedAt: text("confirmed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  confirmedBy: text("confirmed_by"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("supplier_product_aliases_identity_unique").on(table.provider, table.secondaryType, table.secondaryId),
  index("supplier_product_aliases_barcode_idx").on(table.canonicalBarcode, table.productId),
]);

export const inventoryOperations = sqliteTable("inventory_operations", {
  id: text("id").primaryKey(),
  documentId: text("document_id"),
  operationType: text("operation_type").notNull().default("ingress"),
  status: text("status").notNull().default("pending"),
  reversalOf: text("reversal_of"),
  reason: text("reason"),
  confirmedBy: text("confirmed_by"),
  lineCount: integer("line_count").notNull().default(0),
  totalUnits: integer("total_units").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  confirmedAt: text("confirmed_at"),
  verificationStatus: text("verification_status").notNull().default("pending"),
}, (table) => [
  index("inventory_operations_history_idx").on(table.confirmedAt, table.id),
  index("inventory_operations_document_idx").on(table.documentId, table.status),
]);

export const inventoryMovements = sqliteTable("inventory_movements", {
  id: text("id").primaryKey(),
  operationId: text("operation_id").notNull(),
  originalMovementId: text("original_movement_id"),
  documentLineId: text("document_line_id"),
  productId: integer("product_id").notNull(),
  productName: text("product_name").notNull(),
  barcode: text("barcode"),
  canonicalBarcode: text("canonical_barcode"),
  secondaryId: text("secondary_id"),
  secondaryType: text("secondary_type"),
  previousQuantity: integer("previous_quantity").notNull(),
  quantityChange: integer("quantity_change").notNull(),
  conversion: integer("conversion").notNull().default(1),
  resultingQuantity: integer("resulting_quantity").notNull(),
  barcodeMethod: text("barcode_method"),
  barcodeSource: text("barcode_source"),
  confirmedBy: text("confirmed_by"),
  reason: text("reason"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("inventory_movements_operation_line_unique").on(table.operationId, table.documentLineId),
  index("inventory_movements_product_idx").on(table.productId, table.createdAt),
  index("inventory_movements_operation_idx").on(table.operationId, table.id),
]);

export const importJobs = sqliteTable("import_jobs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  fileName: text("file_name").notNull(),
  sheetName: text("sheet_name"),
  strategy: text("strategy").notNull().default("update"),
  status: text("status").notNull().default("queued"),
  totalRows: integer("total_rows").notNull().default(0),
  processedRows: integer("processed_rows").notNull().default(0),
  importedCount: integer("imported_count").notNull().default(0),
  updatedCount: integer("updated_count").notNull().default(0),
  skippedCount: integer("skipped_count").notNull().default(0),
  conflictCount: integer("conflict_count").notNull().default(0),
  errorCount: integer("error_count").notNull().default(0),
  incompleteCount: integer("incomplete_count").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
  restoredAt: text("restored_at"),
});

export const importJobRows = sqliteTable("import_job_rows", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  importId: integer("import_id").notNull(),
  rowNumber: integer("row_number").notNull(),
  name: text("name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  code: text("code"),
  purchasePriceUsdCents: integer("purchase_price_usd_cents"),
  weightMilliLb: integer("weight_milli_lb"),
  quantityAvailable: integer("quantity_available"),
  minimumStock: integer("minimum_stock"),
  minimumStockEnabled: integer("minimum_stock_enabled", { mode: "boolean" }),
  hasCode: integer("has_code", { mode: "boolean" }).notNull().default(false),
  hasPurchasePrice: integer("has_purchase_price", { mode: "boolean" }).notNull().default(false),
  hasWeight: integer("has_weight", { mode: "boolean" }).notNull().default(false),
  hasQuantity: integer("has_quantity", { mode: "boolean" }).notNull().default(false),
  hasMinimumStock: integer("has_minimum_stock", { mode: "boolean" }).notNull().default(false),
  processed: integer("processed", { mode: "boolean" }).notNull().default(false),
  claimToken: text("claim_token"),
  claimedAt: text("claimed_at"),
  outcome: text("outcome"),
  message: text("message"),
}, (table) => [
  index("import_job_rows_pending_idx").on(table.importId, table.processed, table.id),
  index("import_job_rows_claim_idx").on(table.importId, table.processed, table.claimedAt, table.id),
]);

export const importBackups = sqliteTable("import_backups", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  importId: integer("import_id").notNull(),
  productCount: integer("product_count").notNull().default(0),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const importBackupProducts = sqliteTable("import_backup_products", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  backupId: integer("backup_id").notNull(),
  originalId: integer("original_id").notNull(),
  name: text("name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  code: text("code"),
  purchasePriceUsdCents: integer("purchase_price_usd_cents"),
  weightMilliLb: integer("weight_milli_lb"),
  quantityAvailable: integer("quantity_available").notNull().default(0),
  minimumStock: integer("minimum_stock").notNull().default(0),
  minimumStockEnabled: integer("minimum_stock_enabled", { mode: "boolean" }).notNull().default(false),
  restockPurchasedAt: text("restock_purchased_at"),
  zeroStockSince: text("zero_stock_since"),
  version: integer("version").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [index("import_backup_products_backup_idx").on(table.backupId, table.originalId)]);

export const productDeletionJobs = sqliteTable("product_deletion_jobs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  status: text("status").notNull().default("queued"),
  totalProducts: integer("total_products").notNull().default(0),
  processedProducts: integer("processed_products").notNull().default(0),
  deletedProducts: integer("deleted_products").notNull().default(0),
  preservedProducts: integer("preserved_products").notNull().default(0),
  backupImportId: integer("backup_import_id"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  completedAt: text("completed_at"),
});

export const productDeletionRows = sqliteTable("product_deletion_rows", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  deletionId: integer("deletion_id").notNull(),
  productId: integer("product_id").notNull(),
  processed: integer("processed", { mode: "boolean" }).notNull().default(false),
  claimToken: text("claim_token"),
  claimedAt: text("claimed_at"),
  outcome: text("outcome"),
}, (table) => [
  index("product_deletion_rows_pending_idx").on(table.deletionId, table.processed, table.id),
  index("product_deletion_rows_claim_idx").on(table.deletionId, table.processed, table.claimedAt, table.id),
]);
