"use client";

import { AlertCircle, CalendarDays, ChevronLeft, ExternalLink, Loader2, MapPin, Package, ReceiptText, RefreshCw, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";

type Context = { accountId: string; contactId: string; conversationId: string };
type Order = { id: string; orderNumber: string; orderType: string; status: string; total: number; paidTotal: number; balance: number; paymentStatus: string; deliveryMethod: string | null; deliveryDate: string | null; createdAt: string };
type Customer = { id: string; name: string; phone: string | null; customerStatus: string; province: string | null; canton: string | null; district: string | null; defaultDeliveryAddress: string | null; locationUrl: string | null; locationReference: string | null; latitude: number | null; longitude: number | null; preferredPaymentMethod: string | null; ordersCount: number; lastOrderDate: string | null };
type Panel = { customer: Customer; activeOrders: Order[]; recentOrders: Order[]; conversationOrders: Order[] };
type Detail = { order: Order & { deliveryAddress: string | null; deliveryInstructions: string | null; province: string | null; canton: string | null; district: string | null; locationUrl: string | null; latitude: number | null; longitude: number | null; expectedPaymentMethod: string | null; deliveryNotes: string | null; specialOrderStatus: string | null; lines: Array<{ product_name_snapshot: string; presentation_snapshot: string | null; quantity: number; unit_price_original: number | null; unit_price_sold: number; discount_amount: number; line_total: number }>; payments: Array<{ amount: number; method: string; payment_type: string; reference: string | null; created_at: string }> } };

const money = new Intl.NumberFormat("es-CR", { style: "currency", currency: "CRC", maximumFractionDigits: 0 });
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-CR", { dateStyle: "medium" }).format(new Date(value)) : "—";
function query(context: Context) { const params = new URLSearchParams(); if (context.accountId) params.set("account_id", context.accountId); if (context.contactId) params.set("contact_id", context.contactId); if (context.conversationId) params.set("conversation_id", context.conversationId); return params.toString(); }
function mapUrl(latitude: number | null, longitude: number | null) { return latitude != null && longitude != null ? `https://www.google.com/maps?q=${latitude},${longitude}` : null; }

export function CrmPanelClient({ context, userName }: { context: Context; userName: string }) {
  const params = useMemo(() => query(context), [context]);
  const [panel, setPanel] = useState<Panel | null>(null);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); setDetail(null); try { const response = await fetch(`/api/operations/crm-panel?${params}`, { cache: "no-store" }); const body = await response.json() as Panel & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || "No se pudo consultar el cliente."); setPanel(body); } catch (cause) { setPanel(null); setError(cause instanceof Error ? cause.message : "No se pudo consultar el cliente."); } finally { setLoading(false); } }, [params]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function openOrder(id: string) { setLoadingDetail(true); setError(null); try { const response = await fetch(`/api/operations/crm-panel/orders/${encodeURIComponent(id)}?${params}`, { cache: "no-store" }); const body = await response.json() as Detail & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || "No se pudo abrir el pedido."); setDetail(body); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo abrir el pedido."); } finally { setLoadingDetail(false); } }
  if (loading) return <main className="crm-panel-shell"><div className="crm-panel-loading"><Loader2 className="spin" /> Cargando consulta CRM…</div></main>;
  if (error || !panel) return <main className="crm-panel-shell"><section className="crm-panel-error"><AlertCircle /><div><h1>Consulta CRM</h1><p>{error || "No se encontró información disponible."}</p><button type="button" onClick={() => void load()}><RefreshCw /> Reintentar</button></div></section></main>;
  const { customer } = panel, location = customer.locationUrl || mapUrl(customer.latitude, customer.longitude);
  return <main className="crm-panel-shell"><header className="crm-panel-header"><div><p className="crm-panel-eyebrow"><ShieldCheck /> Solo lectura</p><h1>Consulta CRM</h1><p>Sesión: {userName}</p></div><button className="crm-panel-icon" type="button" aria-label="Actualizar consulta" onClick={() => void load()}><RefreshCw /></button></header>
    <section className="crm-panel-card crm-panel-customer"><div className="crm-panel-title"><UserRound /><div><h2>{customer.name}</h2><p>{customer.phone || "Sin teléfono"} · {customer.customerStatus}</p></div></div><div className="crm-panel-stats"><span><strong>{customer.ordersCount}</strong> pedidos</span><span><strong>{date(customer.lastOrderDate)}</strong> última compra</span></div><details open><summary>Dirección y ubicación</summary><p>{[customer.defaultDeliveryAddress, customer.district, customer.canton, customer.province].filter(Boolean).join(", ") || "Sin dirección registrada"}</p>{customer.locationReference && <p className="crm-panel-muted">{customer.locationReference}</p>}{location && <a className="crm-panel-link" href={location} target="_blank" rel="noreferrer"><MapPin /> Abrir ubicación <ExternalLink /></a>}</details><p className="crm-panel-muted">Pago preferido: {customer.preferredPaymentMethod || "No definido"}</p></section>
    {detail ? <OrderDetail detail={detail} onBack={() => setDetail(null)} /> : <><OrderList title="Pedidos activos" icon={<Package />} orders={panel.activeOrders} onOpen={openOrder} loading={loadingDetail} empty="No hay pedidos activos." />{panel.conversationOrders.length > 0 && <OrderList title="Pedidos vinculados a esta conversación" icon={<ReceiptText />} orders={panel.conversationOrders} onOpen={openOrder} loading={loadingDetail} empty="" />}{panel.recentOrders.length > 0 && <OrderList title="Historial reciente" icon={<CalendarDays />} orders={panel.recentOrders} onOpen={openOrder} loading={loadingDetail} empty="" />}{panel.recentOrders.length === 0 && <section className="crm-panel-card crm-panel-empty"><Package /><p>Este cliente todavía no tiene pedidos.</p></section>}</>}
  </main>;
}

function OrderList({ title, icon, orders, onOpen, loading, empty }: { title: string; icon: ReactNode; orders: Order[]; onOpen: (id: string) => void; loading: boolean; empty: string }) { return <section className="crm-panel-card"><h2 className="crm-panel-section-title">{icon}{title}</h2>{orders.length === 0 ? <p className="crm-panel-muted">{empty}</p> : <div className="crm-panel-orders">{orders.map((order) => <article className="crm-panel-order" key={order.id}><div><strong>{order.orderNumber}</strong><p>{date(order.createdAt)} · {order.status}</p><p>{order.orderType === "SPECIAL_ORDER" ? "Encargo" : "Pedido"} · {order.paymentStatus}</p></div><div className="crm-panel-order-side"><strong>{money.format(order.total)}</strong><span>Saldo {money.format(order.balance)}</span><button type="button" onClick={() => void onOpen(order.id)} disabled={loading}>Ver pedido</button></div></article>)}</div>}</section>; }

function OrderDetail({ detail, onBack }: { detail: Detail; onBack: () => void }) { const order = detail.order, location = order.locationUrl || mapUrl(order.latitude, order.longitude); return <><button className="crm-panel-back" type="button" onClick={onBack}><ChevronLeft /> Volver a pedidos</button><section className="crm-panel-card"><h2 className="crm-panel-section-title"><ReceiptText /> {order.orderNumber}</h2><div className="crm-panel-detail-grid"><span>Estado<strong>{order.status}</strong></span><span>Pago<strong>{order.paymentStatus}</strong></span><span>Total<strong>{money.format(order.total)}</strong></span><span>Saldo<strong>{money.format(order.balance)}</strong></span><span>Entrega<strong>{order.deliveryDate ? date(order.deliveryDate) : "Sin fecha"}</strong></span><span>Método<strong>{order.expectedPaymentMethod || "No definido"}</strong></span></div>{order.specialOrderStatus && <p className="crm-panel-badge">Encargo: {order.specialOrderStatus}</p>}<details open><summary>Productos</summary>{order.lines.map((line, index) => <div className="crm-panel-line" key={`${line.product_name_snapshot}-${index}`}><span><strong>{line.product_name_snapshot}</strong><small>{line.presentation_snapshot || ""} · {line.quantity} unidad(es)</small></span><span>{money.format(line.line_total)}{line.discount_amount > 0 && <small>Descuento {money.format(line.discount_amount)}</small>}</span></div>)}</details><details><summary>Pagos y abonos</summary>{order.payments.length ? order.payments.map((payment, index) => <div className="crm-panel-line" key={`${payment.created_at}-${index}`}><span><strong>{payment.payment_type}</strong><small>{payment.method} · {date(payment.created_at)} {payment.reference ? `· ${payment.reference}` : ""}</small></span><span>{money.format(payment.amount)}</span></div>) : <p className="crm-panel-muted">No hay pagos registrados.</p>}</details><details><summary>Entrega</summary><p>{[order.deliveryAddress, order.district, order.canton, order.province].filter(Boolean).join(", ") || "Sin dirección registrada"}</p>{order.deliveryInstructions && <p className="crm-panel-muted">{order.deliveryInstructions}</p>}{order.deliveryNotes && <p className="crm-panel-muted">{order.deliveryNotes}</p>}{location && <a className="crm-panel-link" href={location} target="_blank" rel="noreferrer"><MapPin /> Abrir ubicación <ExternalLink /></a>}</details></section><section className="crm-panel-card crm-panel-readonly"><WalletCards /><p>Vista informativa. No se pueden crear ni modificar pedidos, pagos, clientes o inventario desde este panel.</p></section></>; }
